[package]
name = "evm-state-types"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
alloy-sol-types = "1.3"
bincode = { workspace = true }
serde = { workspace = true }
hex = { workspace = true }
