// This file is @generated by prost-build.
/// InfoRequest is the request type for the Info RPC.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InfoRequest {}
/// InfoResponse is the response type for the Info RPC.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InfoResponse {
    /// state_transition_verifier_key is the hex-encoded verifier key used for
    /// state transition proof verification.
    #[prost(string, tag = "1")]
    pub state_transition_verifier_key: ::prost::alloc::string::String,
    /// state_membership_verifier_key is the hex-encoded verifier key used for
    /// state membership proof verification.
    #[prost(string, tag = "2")]
    pub state_membership_verifier_key: ::prost::alloc::string::String,
}
/// ProveStateTransitionRequest is the request type for ProveStateTransition.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveStateTransitionRequest {
    /// client_id identifies the client for which to generate the state transition
    /// proof. For EVM chains this is the Tendermint light client contract address.
    /// For Tendermint chains this is the client ID.
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
}
/// ProveStateTransitionResponse is the response type for ProveStateTransition.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveStateTransitionResponse {
    /// proof contains the zero-knowledge proof bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
    /// public_values contains the public inputs used for proof verification.
    #[prost(bytes = "vec", tag = "2")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
}
/// ProveStateMembershipRequest is the request type for ProveStateMembership.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveStateMembershipRequest {
    /// client_id identifies the client for which to generate the state membership
    /// proof. For EVM chains this is the Tendermint light client contract address.
    /// For Tendermint chains this is the client ID.
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    /// key_paths is the list of storage key paths to prove membership for.
    #[prost(string, repeated, tag = "2")]
    pub key_paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// ProveStateMembershipResponse is the response type for ProveStateMembership.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProveStateMembershipResponse {
    /// proof contains the zero-knowledge proof bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
    /// height is the block height at which the membership proof was generated.
    #[prost(int64, tag = "2")]
    pub height: i64,
}
/// BlockProof represents a zero-knowledge proof for a single Celestia block.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockProof {
    /// celestia_height is the Celestia block height this proof corresponds to.
    #[prost(uint64, tag = "1")]
    pub celestia_height: u64,
    /// proof_data contains the serialized zero-knowledge proof bytes.
    #[prost(bytes = "vec", tag = "2")]
    pub proof_data: ::prost::alloc::vec::Vec<u8>,
    /// public_values contains the public inputs used for proof verification.
    #[prost(bytes = "vec", tag = "3")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    /// created_at is the Unix timestamp (in seconds) when this proof was generated.
    #[prost(uint64, tag = "4")]
    pub created_at: u64,
}
/// RangeProof represents an aggregated zero-knowledge proof covering multiple
/// Celestia blocks within a height range.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RangeProof {
    /// start_height is the starting Celestia block height (inclusive).
    #[prost(uint64, tag = "1")]
    pub start_height: u64,
    /// end_height is the ending Celestia block height (inclusive).
    #[prost(uint64, tag = "2")]
    pub end_height: u64,
    /// proof_data contains the serialized aggregated zero-knowledge proof bytes.
    #[prost(bytes = "vec", tag = "3")]
    pub proof_data: ::prost::alloc::vec::Vec<u8>,
    /// public_values contains the public inputs used for proof verification.
    #[prost(bytes = "vec", tag = "4")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    /// created_at is the Unix timestamp (in seconds) when this proof was generated.
    #[prost(uint64, tag = "5")]
    pub created_at: u64,
}
/// MembershipProof represents a zero-knowledge proof for state membership
/// verification.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MembershipProof {
    /// proof_data contains the serialized zero-knowledge proof bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub proof_data: ::prost::alloc::vec::Vec<u8>,
    /// public_values contains the public inputs used for proof verification.
    #[prost(bytes = "vec", tag = "2")]
    pub public_values: ::prost::alloc::vec::Vec<u8>,
    /// created_at is the Unix timestamp (in seconds) when this proof was generated.
    #[prost(uint64, tag = "3")]
    pub created_at: u64,
}
/// GetBlockProofRequest is the request type for GetBlockProof.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockProofRequest {
    /// celestia_height is the Celestia block height for which to retrieve the proof.
    #[prost(uint64, tag = "1")]
    pub celestia_height: u64,
}
/// GetBlockProofResponse is the response type for GetBlockProof.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockProofResponse {
    /// proof is the block proof for the requested height.
    #[prost(message, optional, tag = "1")]
    pub proof: ::core::option::Option<BlockProof>,
}
/// GetBlockProofsInRangeRequest is the request type for GetBlockProofsInRange.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockProofsInRangeRequest {
    /// start_height is the starting Celestia block height (inclusive).
    #[prost(uint64, tag = "1")]
    pub start_height: u64,
    /// end_height is the ending Celestia block height (inclusive).
    #[prost(uint64, tag = "2")]
    pub end_height: u64,
}
/// GetBlockProofsInRangeResponse is the response type for GetBlockProofsInRange.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBlockProofsInRangeResponse {
    /// proofs is the list of block proofs within the requested range.
    #[prost(message, repeated, tag = "1")]
    pub proofs: ::prost::alloc::vec::Vec<BlockProof>,
}
/// GetLatestBlockProofRequest is the request type for GetLatestBlockProof.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLatestBlockProofRequest {}
/// GetLatestBlockProofResponse is the response type for GetLatestBlockProof.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLatestBlockProofResponse {
    /// proof is the most recently generated block proof.
    #[prost(message, optional, tag = "1")]
    pub proof: ::core::option::Option<BlockProof>,
    /// has_proof indicates whether a proof exists.
    #[prost(bool, tag = "2")]
    pub has_proof: bool,
}
/// GetMembershipProofRequest is the request type for GetMembershipProof.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMembershipProofRequest {
    /// height is the block height for which to retrieve the membership proof.
    #[prost(uint64, tag = "1")]
    pub height: u64,
}
/// GetMembershipProofResponse is the response type for GetMembershipProof.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMembershipProofResponse {
    /// proof is the membership proof for the requested height.
    #[prost(message, optional, tag = "1")]
    pub proof: ::core::option::Option<MembershipProof>,
}
/// GetLatestMembershipProofRequest is the request type for
/// GetLatestMembershipProof.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLatestMembershipProofRequest {}
/// GetLatestMembershipProofResponse is the response type for
/// GetLatestMembershipProof.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLatestMembershipProofResponse {
    /// proof is the most recently generated membership proof.
    #[prost(message, optional, tag = "1")]
    pub proof: ::core::option::Option<MembershipProof>,
    /// has_proof indicates whether a proof exists.
    #[prost(bool, tag = "2")]
    pub has_proof: bool,
}
/// GetRangeProofsRequest is the request type for GetRangeProofs.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRangeProofsRequest {
    /// start_height is the starting Celestia block height (inclusive).
    #[prost(uint64, tag = "1")]
    pub start_height: u64,
    /// end_height is the ending Celestia block height (inclusive).
    #[prost(uint64, tag = "2")]
    pub end_height: u64,
}
/// GetRangeProofsResponse is the response type for GetRangeProofs.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRangeProofsResponse {
    /// proofs is the list of aggregated range proofs covering the requested range.
    #[prost(message, repeated, tag = "1")]
    pub proofs: ::prost::alloc::vec::Vec<RangeProof>,
}
/// Generated client implementations.
pub mod prover_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Prover defines the gRPC prover service for generating and querying
    /// zero-knowledge proofs for state transitions and state membership.
    #[derive(Debug, Clone)]
    pub struct ProverClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ProverClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ProverClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ProverClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            ProverClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Info returns general information about the prover service including
        /// verification keys for state transition and state membership proofs.
        pub async fn info(
            &mut self,
            request: impl tonic::IntoRequest<super::InfoRequest>,
        ) -> std::result::Result<tonic::Response<super::InfoResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/celestia.prover.v1.Prover/Info",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("celestia.prover.v1.Prover", "Info"));
            self.inner.unary(req, path, codec).await
        }
        /// ProveStateTransition generates a zero-knowledge proof for a state
        /// transition of the specified client.
        pub async fn prove_state_transition(
            &mut self,
            request: impl tonic::IntoRequest<super::ProveStateTransitionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProveStateTransitionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/celestia.prover.v1.Prover/ProveStateTransition",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("celestia.prover.v1.Prover", "ProveStateTransition"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// ProveStateMembership generates a zero-knowledge proof for state
        /// membership verification of the specified key paths.
        pub async fn prove_state_membership(
            &mut self,
            request: impl tonic::IntoRequest<super::ProveStateMembershipRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProveStateMembershipResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/celestia.prover.v1.Prover/ProveStateMembership",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("celestia.prover.v1.Prover", "ProveStateMembership"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GetBlockProof retrieves a single block proof by Celestia height.
        pub async fn get_block_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBlockProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBlockProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/celestia.prover.v1.Prover/GetBlockProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("celestia.prover.v1.Prover", "GetBlockProof"));
            self.inner.unary(req, path, codec).await
        }
        /// GetBlockProofsInRange retrieves multiple block proofs within a
        /// specified height range.
        pub async fn get_block_proofs_in_range(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBlockProofsInRangeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBlockProofsInRangeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/celestia.prover.v1.Prover/GetBlockProofsInRange",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("celestia.prover.v1.Prover", "GetBlockProofsInRange"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GetLatestBlockProof retrieves the most recently generated block proof.
        pub async fn get_latest_block_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLatestBlockProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLatestBlockProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/celestia.prover.v1.Prover/GetLatestBlockProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("celestia.prover.v1.Prover", "GetLatestBlockProof"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GetMembershipProof retrieves a state membership proof for a specific
        /// height.
        pub async fn get_membership_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMembershipProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMembershipProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/celestia.prover.v1.Prover/GetMembershipProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("celestia.prover.v1.Prover", "GetMembershipProof"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GetLatestMembershipProof retrieves the most recently generated state
        /// membership proof.
        pub async fn get_latest_membership_proof(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLatestMembershipProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLatestMembershipProofResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/celestia.prover.v1.Prover/GetLatestMembershipProof",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "celestia.prover.v1.Prover",
                        "GetLatestMembershipProof",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// GetRangeProofs retrieves aggregated range proofs covering a specified
        /// height range.
        pub async fn get_range_proofs(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRangeProofsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRangeProofsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/celestia.prover.v1.Prover/GetRangeProofs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("celestia.prover.v1.Prover", "GetRangeProofs"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod prover_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ProverServer.
    #[async_trait]
    pub trait Prover: Send + Sync + 'static {
        /// Info returns general information about the prover service including
        /// verification keys for state transition and state membership proofs.
        async fn info(
            &self,
            request: tonic::Request<super::InfoRequest>,
        ) -> std::result::Result<tonic::Response<super::InfoResponse>, tonic::Status>;
        /// ProveStateTransition generates a zero-knowledge proof for a state
        /// transition of the specified client.
        async fn prove_state_transition(
            &self,
            request: tonic::Request<super::ProveStateTransitionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProveStateTransitionResponse>,
            tonic::Status,
        >;
        /// ProveStateMembership generates a zero-knowledge proof for state
        /// membership verification of the specified key paths.
        async fn prove_state_membership(
            &self,
            request: tonic::Request<super::ProveStateMembershipRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ProveStateMembershipResponse>,
            tonic::Status,
        >;
        /// GetBlockProof retrieves a single block proof by Celestia height.
        async fn get_block_proof(
            &self,
            request: tonic::Request<super::GetBlockProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBlockProofResponse>,
            tonic::Status,
        >;
        /// GetBlockProofsInRange retrieves multiple block proofs within a
        /// specified height range.
        async fn get_block_proofs_in_range(
            &self,
            request: tonic::Request<super::GetBlockProofsInRangeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBlockProofsInRangeResponse>,
            tonic::Status,
        >;
        /// GetLatestBlockProof retrieves the most recently generated block proof.
        async fn get_latest_block_proof(
            &self,
            request: tonic::Request<super::GetLatestBlockProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLatestBlockProofResponse>,
            tonic::Status,
        >;
        /// GetMembershipProof retrieves a state membership proof for a specific
        /// height.
        async fn get_membership_proof(
            &self,
            request: tonic::Request<super::GetMembershipProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMembershipProofResponse>,
            tonic::Status,
        >;
        /// GetLatestMembershipProof retrieves the most recently generated state
        /// membership proof.
        async fn get_latest_membership_proof(
            &self,
            request: tonic::Request<super::GetLatestMembershipProofRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLatestMembershipProofResponse>,
            tonic::Status,
        >;
        /// GetRangeProofs retrieves aggregated range proofs covering a specified
        /// height range.
        async fn get_range_proofs(
            &self,
            request: tonic::Request<super::GetRangeProofsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetRangeProofsResponse>,
            tonic::Status,
        >;
    }
    /// Prover defines the gRPC prover service for generating and querying
    /// zero-knowledge proofs for state transitions and state membership.
    #[derive(Debug)]
    pub struct ProverServer<T: Prover> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: Prover> ProverServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ProverServer<T>
    where
        T: Prover,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/celestia.prover.v1.Prover/Info" => {
                    #[allow(non_camel_case_types)]
                    struct InfoSvc<T: Prover>(pub Arc<T>);
                    impl<T: Prover> tonic::server::UnaryService<super::InfoRequest>
                    for InfoSvc<T> {
                        type Response = super::InfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Prover>::info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = InfoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/celestia.prover.v1.Prover/ProveStateTransition" => {
                    #[allow(non_camel_case_types)]
                    struct ProveStateTransitionSvc<T: Prover>(pub Arc<T>);
                    impl<
                        T: Prover,
                    > tonic::server::UnaryService<super::ProveStateTransitionRequest>
                    for ProveStateTransitionSvc<T> {
                        type Response = super::ProveStateTransitionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProveStateTransitionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Prover>::prove_state_transition(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ProveStateTransitionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/celestia.prover.v1.Prover/ProveStateMembership" => {
                    #[allow(non_camel_case_types)]
                    struct ProveStateMembershipSvc<T: Prover>(pub Arc<T>);
                    impl<
                        T: Prover,
                    > tonic::server::UnaryService<super::ProveStateMembershipRequest>
                    for ProveStateMembershipSvc<T> {
                        type Response = super::ProveStateMembershipResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProveStateMembershipRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Prover>::prove_state_membership(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = ProveStateMembershipSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/celestia.prover.v1.Prover/GetBlockProof" => {
                    #[allow(non_camel_case_types)]
                    struct GetBlockProofSvc<T: Prover>(pub Arc<T>);
                    impl<
                        T: Prover,
                    > tonic::server::UnaryService<super::GetBlockProofRequest>
                    for GetBlockProofSvc<T> {
                        type Response = super::GetBlockProofResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBlockProofRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Prover>::get_block_proof(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetBlockProofSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/celestia.prover.v1.Prover/GetBlockProofsInRange" => {
                    #[allow(non_camel_case_types)]
                    struct GetBlockProofsInRangeSvc<T: Prover>(pub Arc<T>);
                    impl<
                        T: Prover,
                    > tonic::server::UnaryService<super::GetBlockProofsInRangeRequest>
                    for GetBlockProofsInRangeSvc<T> {
                        type Response = super::GetBlockProofsInRangeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBlockProofsInRangeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Prover>::get_block_proofs_in_range(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetBlockProofsInRangeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/celestia.prover.v1.Prover/GetLatestBlockProof" => {
                    #[allow(non_camel_case_types)]
                    struct GetLatestBlockProofSvc<T: Prover>(pub Arc<T>);
                    impl<
                        T: Prover,
                    > tonic::server::UnaryService<super::GetLatestBlockProofRequest>
                    for GetLatestBlockProofSvc<T> {
                        type Response = super::GetLatestBlockProofResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetLatestBlockProofRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Prover>::get_latest_block_proof(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetLatestBlockProofSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/celestia.prover.v1.Prover/GetMembershipProof" => {
                    #[allow(non_camel_case_types)]
                    struct GetMembershipProofSvc<T: Prover>(pub Arc<T>);
                    impl<
                        T: Prover,
                    > tonic::server::UnaryService<super::GetMembershipProofRequest>
                    for GetMembershipProofSvc<T> {
                        type Response = super::GetMembershipProofResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetMembershipProofRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Prover>::get_membership_proof(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetMembershipProofSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/celestia.prover.v1.Prover/GetLatestMembershipProof" => {
                    #[allow(non_camel_case_types)]
                    struct GetLatestMembershipProofSvc<T: Prover>(pub Arc<T>);
                    impl<
                        T: Prover,
                    > tonic::server::UnaryService<super::GetLatestMembershipProofRequest>
                    for GetLatestMembershipProofSvc<T> {
                        type Response = super::GetLatestMembershipProofResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::GetLatestMembershipProofRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Prover>::get_latest_membership_proof(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetLatestMembershipProofSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/celestia.prover.v1.Prover/GetRangeProofs" => {
                    #[allow(non_camel_case_types)]
                    struct GetRangeProofsSvc<T: Prover>(pub Arc<T>);
                    impl<
                        T: Prover,
                    > tonic::server::UnaryService<super::GetRangeProofsRequest>
                    for GetRangeProofsSvc<T> {
                        type Response = super::GetRangeProofsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetRangeProofsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Prover>::get_range_proofs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetRangeProofsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: Prover> Clone for ProverServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: Prover> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: Prover> tonic::server::NamedService for ProverServer<T> {
        const NAME: &'static str = "celestia.prover.v1.Prover";
    }
}
